version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lamp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lamp_app
      MYSQL_USER: yashnikov
      MYSQL_PASSWORD: valeriypassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "3306:3306"

  web:
    build: ./web
    container_name: lamp_php
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./web/public:/var/www/html
      - ./web/src:/var/www/src
    environment:
      DB_HOST: db
      DB_NAME: lamp_app
      DB_USER: yashnikov
      DB_PASS: valeriypassword

volumes:
  db_data:

